server:
  port: 8761

spring:
  security:
    user:
      name: eureka
      password: password

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false

  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


#Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
      base-path: /actuator/discovery

#Tracing
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  level:
    org:
      springframework:
        web: debug
        security: debug
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

