version: '3'
services:
  ### Postgres database for Inventory
  db-inventory:
    container_name: db-inventory
    image: postgres:16.1
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_inventory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gibb
    ports:
      - 5431:5432
    expose:
      - 5431
    command: -p 5431

  ### MySQL database for Orders
  db-orders:
    container_name: db-orders
    image: mysql:8.0.35
    restart: unless-stopped
    environment:
      MYSQL_DB: ms_orders
      MYSQL_ROOT_PASSWORD: gibb
    ports:
      - 3307:3306
    expose:
      - 3307

  ### Postgres database for Inventory
  db-products:
    container_name: db-products
    image: postgres:16.1
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gibb
    ports:
      - 5432:5432
    expose:
      - 5432
    command: -p 5432

  ### Postgres database for Keycloak
  db-keycloak:
    container_name: db-keycloak
    image: postgres:16.1
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gibb
    ports:
      - 5433:5432
    expose:
      - 5433
    command: -p 5433

  ### Keycloak
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:23.0.0
    command: ["start-dev"]
    ports:
      - 8181:8181
    expose:
      - 8181
    depends_on:
      - db-keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db-keycloak
      DB_DATABASE: db_keycloak
      DB_PORT: 5433
      DB_USER: postgres
      DB_PASSWORD: gibb
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8181


