services:
  db-inventory:
    container_name: db-inventory
    image: postgres:16.1
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_inventory
      POSTGRES_USER: gibbssonfarias
      POSTGRES_PASSWORD: gibb246
    ports:
      - "5431:5432"
    volumes:
      - postgres_inventory_data:/var/lib/postgresql/data

  db-orders:
    container_name: db-orders
    image: mysql:8.0.35
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ms_orders
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_orders_data:/var/lib/mysql

  db-products:
    container_name: db-products
    image: postgres:16.1
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_products
      POSTGRES_USER: gibbssonfarias
      POSTGRES_PASSWORD: gibb246
    ports:
      - "5430:5432"
    volumes:
      - postgres_products_data:/var/lib/postgresql/data


  db-keycloak:
    container_name: db-keycloak
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_keycloak
      POSTGRES_USER: gibbssonfarias
      POSTGRES_PASSWORD: gibb246
    ports:
      - "5433:5432"
    expose:
      - 5433
    command: -p 5433

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:23.0.0
    command: ["start-dev"]
    ports:
      - "8181:8181"
    expose:
      - 8181
    depends_on:
      - db-keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db-keycloak
      DB_DATABASE: db_keycloak
      DB_PORT: 5433
      DB_USER: postgres
      DB_PASSWORD: gibb
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8181


  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  zipkin:
    container_name: zipkin-01
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.46.0
    ports:
      - "9090:9090"
    volumes:
      - ./files/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    container_name: grafana
    image: grafana/grafana-oss:10.0.3
    restart: unless-stopped
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    links:
      - prometheus
    volumes:
      - ./files/grafana:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SECURITY_ADMIN_USER: admin
    depends_on:
      - prometheus


volumes:
  postgres_inventory_data:
  postgres_products_data:
  postgres_keycloak_data:
  mysql_orders_data: