server:
  port: 8090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: inventory-service
          uri: http://localhost:8699
          predicates:
            - Path=/api/v1/inventory/**

        - id: orders-service
          uri: http://localhost:8988
          predicates:
            - Path=/api/v1/orders/**

        - id: products-service
          uri: http://localhost:8877
          predicates:
            - Path=/api/v1/products/**
