server:
  port: 8877

spring:
  application:
    name: products-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ms_products
    username: postgres
    password: gibb
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

#Eureka client
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}